import { useEffect, useMemo, useState } from 'react';

/**
 * The contracted state, drawn as a living map behind the dashboard.
 *
 * Depth comes from stacking the same outline several times on the Z axis inside a
 * perspective container — real 3D transforms, composited by the GPU, rather than a
 * WebGL scene and a mesh for what is ultimately a backdrop.
 *
 * Districts carry the data: the brighter a district glows, the more open calls sit
 * in it. That makes the artwork a reading of the contract rather than decoration,
 * and it is why the map is worth its bytes.
 *
 * Geometry is generated by scripts/build-maps.mjs from geoBoundaries ADM2 (ODbL).
 */

const LAYERS = 7; // extrusion slices; more reads as thicker, and costs more to composite

export default function StateMap({ stateId, intensity }) {
  const [map, setMap] = useState(null);

  // Loaded on demand so a state without geometry costs nothing, and so the map
  // never delays first paint of the figures.
  useEffect(() => {
    let cancelled = false;
    setMap(null);
    import(`../data/maps/${stateId}.js`)
      .then((m) => { if (!cancelled) setMap({ viewBox: m.VIEW_BOX, districts: m.DISTRICTS }); })
      .catch(() => { /* no geometry for this state; the ambient layer carries on */ });
    return () => { cancelled = true; };
  }, [stateId]);

  const shaded = useMemo(() => {
    if (!map) return [];
    const peak = Math.max(1, ...Object.values(intensity ?? {}));
    return map.districts.map((d) => ({
      ...d,
      // Square-rooted so a single dominant district does not flatten the rest.
      heat: Math.sqrt((intensity?.[d.name] ?? 0) / peak),
    }));
  }, [map, intensity]);

  if (!map) return null;

  return (
    <div className="statemap" aria-hidden="true">
      <div className="statemap-stage">
        {/* Extrusion: copies pushed back in Z, darkest at the base. */}
        {Array.from({ length: LAYERS }, (_, i) => (
          <svg
            key={i}
            className="statemap-slice"
            viewBox={map.viewBox}
            preserveAspectRatio="xMidYMid meet"
            style={{ '--z': `${-(LAYERS - i) * 3}px`, '--slice': i / LAYERS }}
          >
            {map.districts.map((d) => (
              <path key={d.name} d={d.path} />
            ))}
          </svg>
        ))}

        {/* Face: the lit top surface, with per-district heat. */}
        <svg
          className="statemap-face"
          viewBox={map.viewBox}
          preserveAspectRatio="xMidYMid meet"
        >
          <defs>
            <linearGradient id="mapFace" x1="0" y1="0" x2="0.4" y2="1">
              <stop offset="0%" stopColor="var(--kerala-light)" />
              <stop offset="100%" stopColor="var(--kerala-deep)" />
            </linearGradient>
            <filter id="mapGlow" x="-30%" y="-30%" width="160%" height="160%">
              <feGaussianBlur stdDeviation="6" />
            </filter>
          </defs>

          {shaded.map((d, i) => (
            <path
              key={d.name}
              className="statemap-district"
              d={d.path}
              style={{
                '--heat': d.heat.toFixed(3),
                // Staggered so districts breathe in sequence rather than in unison.
                animationDelay: `${(i % 7) * 0.55}s`,
              }}
            />
          ))}
        </svg>

        {/* Service sweep: a soft band crossing the state, like a coverage pass. */}
        <div className="statemap-sweep" />
      </div>
    </div>
  );
}
